# Generated by Django 3.0.5 on 2020-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='outcome_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
